workdir: "/usr/local/var/lib/glusterd2/"
logfile: "/usr/local/var/log/glusterd2/glusterd2.log"
peeraddress: "127.0.0.1:24008"
clientaddress: "127.0.0.1:24007"
etcdcurls: "http://127.0.0.1:2479"
etcdpurls: "http://127.0.0.1:2480"
